package com.gcs.db.businessDao;
// Generated Nov 8, 2017 3:18:55 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Resourceallocations generated by hbm2java
 */
@SuppressWarnings("serial")
public class Resourceallocations implements java.io.Serializable {

	@Id
	@GeneratedValue
	private int resId;
	private int employeeId;
	private int projectId;
	private String allocation;
	private String empId;
	private String employeeName;
	private String projectName;
	private Date projectFrom;
	private Date projectTo;
	private String projectFromStr;
	private String projectToStr;
	private String projectCompleted;
	private String billable;
    private String reportingTo;
    
    

	public String getReportingTo() {
		return reportingTo;
	}

	public void setReportingTo(String reportingTo) {
		this.reportingTo = reportingTo;
	}

	public void setResId(int resId) {
		this.resId = resId;
	}

	public Resourceallocations() {
	}

	public Resourceallocations(int employeeId, int projectId ) {
		this.employeeId = employeeId;
		this.projectId = projectId;
	}

	public Resourceallocations(int employeeId, int projectId, Date projectFrom, Date projectTo,
			String projectCompleted , String billable) {
		this.employeeId = employeeId;
		this.projectId = projectId;
		this.projectFrom = projectFrom;
		this.projectTo = projectTo;
		this.projectCompleted = projectCompleted;
		this.billable = billable;
	}

	public String getBillable() {
		return billable;
	}

	public void setBillable(String billable) {
		this.billable = billable;
	}

	public Integer getResId() {
		return this.resId;
	}

	public void setResId(Integer resId) {
		this.resId = resId;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	

	public int getProjectId() {
		return projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public String getAllocation() {
		return allocation;
	}

	public void setAllocation(String allocation) {
		this.allocation = allocation;
	}

	public Date getProjectFrom() {
		return this.projectFrom;
	}

	public void setProjectFrom(Date projectFrom) {
		this.projectFrom = projectFrom;
	}

	public Date getProjectTo() {
		return this.projectTo;
	}

	public void setProjectTo(Date projectTo) {
		this.projectTo = projectTo;
	}

	public String getProjectCompleted() {
		return this.projectCompleted;
	}

	public void setProjectCompleted(String projectCompleted) {
		this.projectCompleted = projectCompleted;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getEmpId() {
		return empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getProjectFromStr() {
		return projectFromStr;
	}

	public void setProjectFromStr(String projectFromStr) {
		this.projectFromStr = projectFromStr;
	}

	public String getProjectToStr() {
		return projectToStr;
	}

	public void setProjectToStr(String projectToStr) {
		this.projectToStr = projectToStr;
	}

	@Override
	public String toString() {
		return "Resourceallocations [resId=" + resId + ", employeeId=" + employeeId + ", projectId=" + projectId
				+ ", allocation=" + allocation + ", empId=" + empId + ", employeeName=" + employeeName
				+ ", projectName=" + projectName + ", projectFrom=" + projectFrom + ", projectTo=" + projectTo
				+ ", projectFromStr=" + projectFromStr + ", projectToStr=" + projectToStr + ", projectCompleted="
				+ projectCompleted + ", billable=" + billable + "]";
	}

	
	

}
